sudo: false
language: ruby

rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3

# to avoid travis-ci issue since 2015-12-25
before_install:
  - gem update bundler

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.10.gemfile
  - gemfiles/fluentd_v0.12.gemfile

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
